/*
 * RMS_covid_stats_cal
 * returns covid data, such as daily confirmed cases, total deaths, total active cases, total cases, etc.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.RmsCovidStatsCal) {
      root.RmsCovidStatsCal = {};
    }
    root.RmsCovidStatsCal.DailyNewStats = factory(root.RmsCovidStatsCal.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The DailyNewStats model module.
   * @module model/DailyNewStats
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>DailyNewStats</code>.
   * @alias module:model/DailyNewStats
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DailyNewStats</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DailyNewStats} obj Optional instance to populate.
   * @return {module:model/DailyNewStats} The populated <code>DailyNewStats</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('MAX(ac.country_code)'))
        obj.mAXAcCountryCode = ApiClient.convertToType(data['MAX(ac.country_code)'], 'String');
      if (data.hasOwnProperty('lat'))
        obj.lat = ApiClient.convertToType(data['lat'], 'Number');
      if (data.hasOwnProperty('lng'))
        obj.lng = ApiClient.convertToType(data['lng'], 'Number');
      if (data.hasOwnProperty('country'))
        obj.country = ApiClient.convertToType(data['country'], 'String');
      if (data.hasOwnProperty('daily_cases'))
        obj.dailyCases = ApiClient.convertToType(data['daily_cases'], 'Number');
      if (data.hasOwnProperty('daily_deaths'))
        obj.dailyDeaths = ApiClient.convertToType(data['daily_deaths'], 'Number');
      if (data.hasOwnProperty('last_updated'))
        obj.lastUpdated = ApiClient.convertToType(data['last_updated'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} mAXAcCountryCode
   */
  exports.prototype.mAXAcCountryCode = undefined;

  /**
   * @member {Number} lat
   */
  exports.prototype.lat = undefined;

  /**
   * @member {Number} lng
   */
  exports.prototype.lng = undefined;

  /**
   * @member {String} country
   */
  exports.prototype.country = undefined;

  /**
   * @member {Number} dailyCases
   */
  exports.prototype.dailyCases = undefined;

  /**
   * @member {Number} dailyDeaths
   */
  exports.prototype.dailyDeaths = undefined;

  /**
   * @member {String} lastUpdated
   */
  exports.prototype.lastUpdated = undefined;


  return exports;

}));
