/*
 * RMS_covid_stats_cal
 * returns covid data, such as daily confirmed cases, total deaths, total active cases, total cases, etc.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.RmsCovidStatsCal) {
      root.RmsCovidStatsCal = {};
    }
    root.RmsCovidStatsCal.TrendCountry = factory(root.RmsCovidStatsCal.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The TrendCountry model module.
   * @module model/TrendCountry
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>TrendCountry</code>.
   * @alias module:model/TrendCountry
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>TrendCountry</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrendCountry} obj Optional instance to populate.
   * @return {module:model/TrendCountry} The populated <code>TrendCountry</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('countryCode'))
        obj.countryCode = ApiClient.convertToType(data['countryCode'], 'String');
      if (data.hasOwnProperty('country'))
        obj.country = ApiClient.convertToType(data['country'], 'String');
      if (data.hasOwnProperty('total_confirmed'))
        obj.totalConfirmed = ApiClient.convertToType(data['total_confirmed'], 'Number');
      if (data.hasOwnProperty('total_deaths'))
        obj.totalDeaths = ApiClient.convertToType(data['total_deaths'], 'Number');
      if (data.hasOwnProperty('total_recovered'))
        obj.totalRecovered = ApiClient.convertToType(data['total_recovered'], 'Number');
      if (data.hasOwnProperty('last_updated'))
        obj.lastUpdated = ApiClient.convertToType(data['last_updated'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} countryCode
   */
  exports.prototype.countryCode = undefined;

  /**
   * @member {String} country
   */
  exports.prototype.country = undefined;

  /**
   * @member {Number} totalConfirmed
   */
  exports.prototype.totalConfirmed = undefined;

  /**
   * @member {Number} totalDeaths
   */
  exports.prototype.totalDeaths = undefined;

  /**
   * @member {Number} totalRecovered
   */
  exports.prototype.totalRecovered = undefined;

  /**
   * @member {String} lastUpdated
   */
  exports.prototype.lastUpdated = undefined;


  return exports;

}));
