/*
 * RMS_covid_stats_cal
 * returns covid data, such as daily confirmed cases, total deaths, total active cases, total cases, etc.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.RmsCovidStatsCal) {
      root.RmsCovidStatsCal = {};
    }
    root.RmsCovidStatsCal.WorldometerCountry = factory(root.RmsCovidStatsCal.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The WorldometerCountry model module.
   * @module model/WorldometerCountry
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>WorldometerCountry</code>.
   * @alias module:model/WorldometerCountry
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>WorldometerCountry</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WorldometerCountry} obj Optional instance to populate.
   * @return {module:model/WorldometerCountry} The populated <code>WorldometerCountry</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('countrycode'))
        obj.countrycode = ApiClient.convertToType(data['countrycode'], 'String');
      if (data.hasOwnProperty('country'))
        obj.country = ApiClient.convertToType(data['country'], 'String');
      if (data.hasOwnProperty('lat'))
        obj.lat = ApiClient.convertToType(data['lat'], 'Number');
      if (data.hasOwnProperty('lng'))
        obj.lng = ApiClient.convertToType(data['lng'], 'Number');
      if (data.hasOwnProperty('totalConfirmed'))
        obj.totalConfirmed = ApiClient.convertToType(data['totalConfirmed'], 'Number');
      if (data.hasOwnProperty('totalDeaths'))
        obj.totalDeaths = ApiClient.convertToType(data['totalDeaths'], 'Number');
      if (data.hasOwnProperty('totalRecovered'))
        obj.totalRecovered = ApiClient.convertToType(data['totalRecovered'], 'Number');
      if (data.hasOwnProperty('dailyConfirmed'))
        obj.dailyConfirmed = ApiClient.convertToType(data['dailyConfirmed'], 'Number');
      if (data.hasOwnProperty('dailyDeaths'))
        obj.dailyDeaths = ApiClient.convertToType(data['dailyDeaths'], 'Number');
      if (data.hasOwnProperty('activeCases'))
        obj.activeCases = ApiClient.convertToType(data['activeCases'], 'Number');
      if (data.hasOwnProperty('totalCritical'))
        obj.totalCritical = ApiClient.convertToType(data['totalCritical'], 'Number');
      if (data.hasOwnProperty('totalConfirmedPerMillionPopulation'))
        obj.totalConfirmedPerMillionPopulation = ApiClient.convertToType(data['totalConfirmedPerMillionPopulation'], 'Number');
      if (data.hasOwnProperty('totalDeathsPerMillionPopulation'))
        obj.totalDeathsPerMillionPopulation = ApiClient.convertToType(data['totalDeathsPerMillionPopulation'], 'Number');
      if (data.hasOwnProperty('FR'))
        obj.FR = ApiClient.convertToType(data['FR'], 'String');
      if (data.hasOwnProperty('PR'))
        obj.PR = ApiClient.convertToType(data['PR'], 'String');
      if (data.hasOwnProperty('lastUpdated'))
        obj.lastUpdated = ApiClient.convertToType(data['lastUpdated'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} countrycode
   */
  exports.prototype.countrycode = undefined;

  /**
   * @member {String} country
   */
  exports.prototype.country = undefined;

  /**
   * @member {Number} lat
   */
  exports.prototype.lat = undefined;

  /**
   * @member {Number} lng
   */
  exports.prototype.lng = undefined;

  /**
   * @member {Number} totalConfirmed
   */
  exports.prototype.totalConfirmed = undefined;

  /**
   * @member {Number} totalDeaths
   */
  exports.prototype.totalDeaths = undefined;

  /**
   * @member {Number} totalRecovered
   */
  exports.prototype.totalRecovered = undefined;

  /**
   * @member {Number} dailyConfirmed
   */
  exports.prototype.dailyConfirmed = undefined;

  /**
   * @member {Number} dailyDeaths
   */
  exports.prototype.dailyDeaths = undefined;

  /**
   * @member {Number} activeCases
   */
  exports.prototype.activeCases = undefined;

  /**
   * @member {Number} totalCritical
   */
  exports.prototype.totalCritical = undefined;

  /**
   * @member {Number} totalConfirmedPerMillionPopulation
   */
  exports.prototype.totalConfirmedPerMillionPopulation = undefined;

  /**
   * @member {Number} totalDeathsPerMillionPopulation
   */
  exports.prototype.totalDeathsPerMillionPopulation = undefined;

  /**
   * @member {String} FR
   */
  exports.prototype.FR = undefined;

  /**
   * @member {String} PR
   */
  exports.prototype.PR = undefined;

  /**
   * @member {String} lastUpdated
   */
  exports.prototype.lastUpdated = undefined;


  return exports;

}));
