/*
 * RMS_covid_stats_cal
 * returns covid data, such as daily confirmed cases, total deaths, total active cases, total cases, etc.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.RmsCovidStatsCal) {
      root.RmsCovidStatsCal = {};
    }
    root.RmsCovidStatsCal.WorldometerGlobal = factory(root.RmsCovidStatsCal.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The WorldometerGlobal model module.
   * @module model/WorldometerGlobal
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>WorldometerGlobal</code>.
   * @alias module:model/WorldometerGlobal
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>WorldometerGlobal</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WorldometerGlobal} obj Optional instance to populate.
   * @return {module:model/WorldometerGlobal} The populated <code>WorldometerGlobal</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('totalConfirmed'))
        obj.totalConfirmed = ApiClient.convertToType(data['totalConfirmed'], 'Number');
      if (data.hasOwnProperty('totalDeaths'))
        obj.totalDeaths = ApiClient.convertToType(data['totalDeaths'], 'Number');
      if (data.hasOwnProperty('totalRecovered'))
        obj.totalRecovered = ApiClient.convertToType(data['totalRecovered'], 'Number');
      if (data.hasOwnProperty('totalNewCases'))
        obj.totalNewCases = ApiClient.convertToType(data['totalNewCases'], 'Number');
      if (data.hasOwnProperty('totalNewDeaths'))
        obj.totalNewDeaths = ApiClient.convertToType(data['totalNewDeaths'], 'Number');
      if (data.hasOwnProperty('totalActiveCases'))
        obj.totalActiveCases = ApiClient.convertToType(data['totalActiveCases'], 'Number');
      if (data.hasOwnProperty('totalCasesPerMillionPop'))
        obj.totalCasesPerMillionPop = ApiClient.convertToType(data['totalCasesPerMillionPop'], 'Number');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} totalConfirmed
   */
  exports.prototype.totalConfirmed = undefined;

  /**
   * @member {Number} totalDeaths
   */
  exports.prototype.totalDeaths = undefined;

  /**
   * @member {Number} totalRecovered
   */
  exports.prototype.totalRecovered = undefined;

  /**
   * @member {Number} totalNewCases
   */
  exports.prototype.totalNewCases = undefined;

  /**
   * @member {Number} totalNewDeaths
   */
  exports.prototype.totalNewDeaths = undefined;

  /**
   * @member {Number} totalActiveCases
   */
  exports.prototype.totalActiveCases = undefined;

  /**
   * @member {Number} totalCasesPerMillionPop
   */
  exports.prototype.totalCasesPerMillionPop = undefined;

  /**
   * @member {String} created
   */
  exports.prototype.created = undefined;


  return exports;

}));
