/*
 * RMS_covid_stats_cal
 * returns covid data, such as daily confirmed cases, total deaths, total active cases, total cases, etc.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DailyNewStats', 'model/NewcasesCountry', 'model/TrendCountry'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/DailyNewStats'), require('../model/NewcasesCountry'), require('../model/TrendCountry'));
  } else {
    // Browser globals (root is window)
    if (!root.RmsCovidStatsCal) {
      root.RmsCovidStatsCal = {};
    }
    root.RmsCovidStatsCal.ANALYTICSApi = factory(root.RmsCovidStatsCal.ApiClient, root.RmsCovidStatsCal.DailyNewStats, root.RmsCovidStatsCal.NewcasesCountry, root.RmsCovidStatsCal.TrendCountry);
  }
}(this, function(ApiClient, DailyNewStats, NewcasesCountry, TrendCountry) {
  'use strict';

  /**
   * ANALYTICS service.
   * @module api/ANALYTICSApi
   * @version 1.0.0
   */

  /**
   * Constructs a new ANALYTICSApi. 
   * @alias module:api/ANALYTICSApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the v5AnalyticsDailyNewStatsGet operation.
     * @callback module:api/ANALYTICSApi~v5AnalyticsDailyNewStatsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/DailyNewStats>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * returns new daily cases and deaths
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit 
     * @param {module:api/ANALYTICSApi~v5AnalyticsDailyNewStatsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/DailyNewStats>}
     */
    this.v5AnalyticsDailyNewStatsGet = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'limit': opts['limit'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = [DailyNewStats];

      return this.apiClient.callApi(
        '/v5/analytics/dailyNewStats', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the v5AnalyticsNewcasesCountryGet operation.
     * @callback module:api/ANALYTICSApi~v5AnalyticsNewcasesCountryGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/NewcasesCountry>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * returns data of covid cases between given startDate and endDate
     * @param {String} startDate 
     * @param {String} endDate 
     * @param {Object} opts Optional parameters
     * @param {String} opts.countryCode 
     * @param {module:api/ANALYTICSApi~v5AnalyticsNewcasesCountryGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/NewcasesCountry>}
     */
    this.v5AnalyticsNewcasesCountryGet = function(startDate, endDate, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'startDate' is set
      if (startDate === undefined || startDate === null) {
        throw new Error("Missing the required parameter 'startDate' when calling v5AnalyticsNewcasesCountryGet");
      }

      // verify the required parameter 'endDate' is set
      if (endDate === undefined || endDate === null) {
        throw new Error("Missing the required parameter 'endDate' when calling v5AnalyticsNewcasesCountryGet");
      }


      var pathParams = {
      };
      var queryParams = {
        'countryCode': opts['countryCode'],
        'startDate': startDate,
        'endDate': endDate,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = [NewcasesCountry];

      return this.apiClient.callApi(
        '/v5/analytics/newcases/country', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the v5AnalyticsTrendCountryGet operation.
     * @callback module:api/ANALYTICSApi~v5AnalyticsTrendCountryGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/TrendCountry>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * returns data of a country between start and end date
     * @param {String} startDate 
     * @param {String} endDate 
     * @param {Object} opts Optional parameters
     * @param {String} opts.countryCode 
     * @param {module:api/ANALYTICSApi~v5AnalyticsTrendCountryGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/TrendCountry>}
     */
    this.v5AnalyticsTrendCountryGet = function(startDate, endDate, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'startDate' is set
      if (startDate === undefined || startDate === null) {
        throw new Error("Missing the required parameter 'startDate' when calling v5AnalyticsTrendCountryGet");
      }

      // verify the required parameter 'endDate' is set
      if (endDate === undefined || endDate === null) {
        throw new Error("Missing the required parameter 'endDate' when calling v5AnalyticsTrendCountryGet");
      }


      var pathParams = {
      };
      var queryParams = {
        'countryCode': opts['countryCode'],
        'startDate': startDate,
        'endDate': endDate,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = [TrendCountry];

      return this.apiClient.callApi(
        '/v5/analytics/trend/country', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
