/*
 * RMS_covid_stats_cal
 * returns covid data, such as daily confirmed cases, total deaths, total active cases, total cases, etc.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RmsCovidStatsCal);
  }
}(this, function(expect, RmsCovidStatsCal) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('NewcasesCountry', function() {
      beforeEach(function() {
        instance = new RmsCovidStatsCal.NewcasesCountry();
      });

      it('should create an instance of NewcasesCountry', function() {
        // TODO: update the code to test NewcasesCountry
        expect(instance).to.be.a(RmsCovidStatsCal.NewcasesCountry);
      });

      it('should have the property country (base name: "country")', function() {
        // TODO: update the code to test the property country
        expect(instance).to.have.property('country');
        // expect(instance.country).to.be(expectedValueLiteral);
      });

      it('should have the property countryCode (base name: "country_code")', function() {
        // TODO: update the code to test the property countryCode
        expect(instance).to.have.property('countryCode');
        // expect(instance.countryCode).to.be(expectedValueLiteral);
      });

      it('should have the property lastUpdated (base name: "last_updated")', function() {
        // TODO: update the code to test the property lastUpdated
        expect(instance).to.have.property('lastUpdated');
        // expect(instance.lastUpdated).to.be(expectedValueLiteral);
      });

      it('should have the property newDeaths (base name: "new_deaths")', function() {
        // TODO: update the code to test the property newDeaths
        expect(instance).to.have.property('newDeaths');
        // expect(instance.newDeaths).to.be(expectedValueLiteral);
      });

      it('should have the property newInfections (base name: "new_infections")', function() {
        // TODO: update the code to test the property newInfections
        expect(instance).to.have.property('newInfections');
        // expect(instance.newInfections).to.be(expectedValueLiteral);
      });

      it('should have the property newRecovered (base name: "new_recovered")', function() {
        // TODO: update the code to test the property newRecovered
        expect(instance).to.have.property('newRecovered');
        // expect(instance.newRecovered).to.be(expectedValueLiteral);
      });

    });
  });

}));
