/*
 * RMS_covid_stats_cal
 * returns covid data, such as daily confirmed cases, total deaths, total active cases, total cases, etc.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RmsCovidStatsCal);
  }
}(this, function(expect, RmsCovidStatsCal) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TrendCountry', function() {
      beforeEach(function() {
        instance = new RmsCovidStatsCal.TrendCountry();
      });

      it('should create an instance of TrendCountry', function() {
        // TODO: update the code to test TrendCountry
        expect(instance).to.be.a(RmsCovidStatsCal.TrendCountry);
      });

      it('should have the property countryCode (base name: "countryCode")', function() {
        // TODO: update the code to test the property countryCode
        expect(instance).to.have.property('countryCode');
        // expect(instance.countryCode).to.be(expectedValueLiteral);
      });

      it('should have the property country (base name: "country")', function() {
        // TODO: update the code to test the property country
        expect(instance).to.have.property('country');
        // expect(instance.country).to.be(expectedValueLiteral);
      });

      it('should have the property totalConfirmed (base name: "total_confirmed")', function() {
        // TODO: update the code to test the property totalConfirmed
        expect(instance).to.have.property('totalConfirmed');
        // expect(instance.totalConfirmed).to.be(expectedValueLiteral);
      });

      it('should have the property totalDeaths (base name: "total_deaths")', function() {
        // TODO: update the code to test the property totalDeaths
        expect(instance).to.have.property('totalDeaths');
        // expect(instance.totalDeaths).to.be(expectedValueLiteral);
      });

      it('should have the property totalRecovered (base name: "total_recovered")', function() {
        // TODO: update the code to test the property totalRecovered
        expect(instance).to.have.property('totalRecovered');
        // expect(instance.totalRecovered).to.be(expectedValueLiteral);
      });

      it('should have the property lastUpdated (base name: "last_updated")', function() {
        // TODO: update the code to test the property lastUpdated
        expect(instance).to.have.property('lastUpdated');
        // expect(instance.lastUpdated).to.be(expectedValueLiteral);
      });

    });
  });

}));
