/*
 * RMS_covid_stats_cal
 * returns covid data, such as daily confirmed cases, total deaths, total active cases, total cases, etc.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RmsCovidStatsCal);
  }
}(this, function(expect, RmsCovidStatsCal) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('WorldometerCountry', function() {
      beforeEach(function() {
        instance = new RmsCovidStatsCal.WorldometerCountry();
      });

      it('should create an instance of WorldometerCountry', function() {
        // TODO: update the code to test WorldometerCountry
        expect(instance).to.be.a(RmsCovidStatsCal.WorldometerCountry);
      });

      it('should have the property countrycode (base name: "countrycode")', function() {
        // TODO: update the code to test the property countrycode
        expect(instance).to.have.property('countrycode');
        // expect(instance.countrycode).to.be(expectedValueLiteral);
      });

      it('should have the property country (base name: "country")', function() {
        // TODO: update the code to test the property country
        expect(instance).to.have.property('country');
        // expect(instance.country).to.be(expectedValueLiteral);
      });

      it('should have the property lat (base name: "lat")', function() {
        // TODO: update the code to test the property lat
        expect(instance).to.have.property('lat');
        // expect(instance.lat).to.be(expectedValueLiteral);
      });

      it('should have the property lng (base name: "lng")', function() {
        // TODO: update the code to test the property lng
        expect(instance).to.have.property('lng');
        // expect(instance.lng).to.be(expectedValueLiteral);
      });

      it('should have the property totalConfirmed (base name: "totalConfirmed")', function() {
        // TODO: update the code to test the property totalConfirmed
        expect(instance).to.have.property('totalConfirmed');
        // expect(instance.totalConfirmed).to.be(expectedValueLiteral);
      });

      it('should have the property totalDeaths (base name: "totalDeaths")', function() {
        // TODO: update the code to test the property totalDeaths
        expect(instance).to.have.property('totalDeaths');
        // expect(instance.totalDeaths).to.be(expectedValueLiteral);
      });

      it('should have the property totalRecovered (base name: "totalRecovered")', function() {
        // TODO: update the code to test the property totalRecovered
        expect(instance).to.have.property('totalRecovered');
        // expect(instance.totalRecovered).to.be(expectedValueLiteral);
      });

      it('should have the property dailyConfirmed (base name: "dailyConfirmed")', function() {
        // TODO: update the code to test the property dailyConfirmed
        expect(instance).to.have.property('dailyConfirmed');
        // expect(instance.dailyConfirmed).to.be(expectedValueLiteral);
      });

      it('should have the property dailyDeaths (base name: "dailyDeaths")', function() {
        // TODO: update the code to test the property dailyDeaths
        expect(instance).to.have.property('dailyDeaths');
        // expect(instance.dailyDeaths).to.be(expectedValueLiteral);
      });

      it('should have the property activeCases (base name: "activeCases")', function() {
        // TODO: update the code to test the property activeCases
        expect(instance).to.have.property('activeCases');
        // expect(instance.activeCases).to.be(expectedValueLiteral);
      });

      it('should have the property totalCritical (base name: "totalCritical")', function() {
        // TODO: update the code to test the property totalCritical
        expect(instance).to.have.property('totalCritical');
        // expect(instance.totalCritical).to.be(expectedValueLiteral);
      });

      it('should have the property totalConfirmedPerMillionPopulation (base name: "totalConfirmedPerMillionPopulation")', function() {
        // TODO: update the code to test the property totalConfirmedPerMillionPopulation
        expect(instance).to.have.property('totalConfirmedPerMillionPopulation');
        // expect(instance.totalConfirmedPerMillionPopulation).to.be(expectedValueLiteral);
      });

      it('should have the property totalDeathsPerMillionPopulation (base name: "totalDeathsPerMillionPopulation")', function() {
        // TODO: update the code to test the property totalDeathsPerMillionPopulation
        expect(instance).to.have.property('totalDeathsPerMillionPopulation');
        // expect(instance.totalDeathsPerMillionPopulation).to.be(expectedValueLiteral);
      });

      it('should have the property FR (base name: "FR")', function() {
        // TODO: update the code to test the property FR
        expect(instance).to.have.property('FR');
        // expect(instance.FR).to.be(expectedValueLiteral);
      });

      it('should have the property PR (base name: "PR")', function() {
        // TODO: update the code to test the property PR
        expect(instance).to.have.property('PR');
        // expect(instance.PR).to.be(expectedValueLiteral);
      });

      it('should have the property lastUpdated (base name: "lastUpdated")', function() {
        // TODO: update the code to test the property lastUpdated
        expect(instance).to.have.property('lastUpdated');
        // expect(instance.lastUpdated).to.be(expectedValueLiteral);
      });

    });
  });

}));
