/*
 * RMS_covid_stats_cal
 * returns covid data, such as daily confirmed cases, total deaths, total active cases, total cases, etc.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DailyNewStats', 'model/NewcasesCountry', 'model/TrendCountry', 'model/WorldometerCountry', 'model/WorldometerGlobal', 'api/ANALYTICSApi', 'api/WORLDOMETERApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/DailyNewStats'), require('./model/NewcasesCountry'), require('./model/TrendCountry'), require('./model/WorldometerCountry'), require('./model/WorldometerGlobal'), require('./api/ANALYTICSApi'), require('./api/WORLDOMETERApi'));
  }
}(function(ApiClient, DailyNewStats, NewcasesCountry, TrendCountry, WorldometerCountry, WorldometerGlobal, ANALYTICSApi, WORLDOMETERApi) {
  'use strict';

  /**
   * returns_covid_data_such_as_daily_confirmed_cases_total_deaths_total_active_cases_total_cases_etc_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var RmsCovidStatsCal = require('index'); // See note below*.
   * var xxxSvc = new RmsCovidStatsCal.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new RmsCovidStatsCal.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new RmsCovidStatsCal.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new RmsCovidStatsCal.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The DailyNewStats model constructor.
     * @property {module:model/DailyNewStats}
     */
    DailyNewStats: DailyNewStats,
    /**
     * The NewcasesCountry model constructor.
     * @property {module:model/NewcasesCountry}
     */
    NewcasesCountry: NewcasesCountry,
    /**
     * The TrendCountry model constructor.
     * @property {module:model/TrendCountry}
     */
    TrendCountry: TrendCountry,
    /**
     * The WorldometerCountry model constructor.
     * @property {module:model/WorldometerCountry}
     */
    WorldometerCountry: WorldometerCountry,
    /**
     * The WorldometerGlobal model constructor.
     * @property {module:model/WorldometerGlobal}
     */
    WorldometerGlobal: WorldometerGlobal,
    /**
     * The ANALYTICSApi service constructor.
     * @property {module:api/ANALYTICSApi}
     */
    ANALYTICSApi: ANALYTICSApi,
    /**
     * The WORLDOMETERApi service constructor.
     * @property {module:api/WORLDOMETERApi}
     */
    WORLDOMETERApi: WORLDOMETERApi
  };

  return exports;
}));
