/*
 * RMS_covid_stats_cal
 * returns covid data, such as daily confirmed cases, total deaths, total active cases, total cases, etc.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RmsCovidStatsCal);
  }
}(this, function(expect, RmsCovidStatsCal) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RmsCovidStatsCal.ANALYTICSApi();
  });

  describe('(package)', function() {
    describe('ANALYTICSApi', function() {
      describe('v5AnalyticsDailyNewStatsGet', function() {
        it('should call v5AnalyticsDailyNewStatsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for v5AnalyticsDailyNewStatsGet call and complete the assertions
          /*
          var opts = {};
          opts.limit = 56;

          instance.v5AnalyticsDailyNewStatsGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(RmsCovidStatsCal.DailyNewStats);
              expect(data.mAXAcCountryCode).to.be.a('string');
              expect(data.mAXAcCountryCode).to.be("");
              expect(data.lat).to.be.a('number');
              expect(data.lat).to.be(0);
              expect(data.lng).to.be.a('number');
              expect(data.lng).to.be(0);
              expect(data.country).to.be.a('string');
              expect(data.country).to.be("");
              expect(data.dailyCases).to.be.a('number');
              expect(data.dailyCases).to.be(0);
              expect(data.dailyDeaths).to.be.a('number');
              expect(data.dailyDeaths).to.be(0);
              expect(data.lastUpdated).to.be.a('string');
              expect(data.lastUpdated).to.be("");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v5AnalyticsNewcasesCountryGet', function() {
        it('should call v5AnalyticsNewcasesCountryGet successfully', function(done) {
          // TODO: uncomment, update parameter values for v5AnalyticsNewcasesCountryGet call and complete the assertions
          /*
          var startDate = "startDate_example";
          var endDate = "endDate_example";
          var opts = {};
          opts.countryCode = "countryCode_example";

          instance.v5AnalyticsNewcasesCountryGet(startDate, endDate, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(RmsCovidStatsCal.NewcasesCountry);
              expect(data.country).to.be.a('string');
              expect(data.country).to.be("");
              expect(data.countryCode).to.be.a('string');
              expect(data.countryCode).to.be("");
              expect(data.lastUpdated).to.be.a('string');
              expect(data.lastUpdated).to.be("");
              expect(data.newDeaths).to.be.a('number');
              expect(data.newDeaths).to.be(0);
              expect(data.newInfections).to.be.a('number');
              expect(data.newInfections).to.be(0);
              expect(data.newRecovered).to.be.a('number');
              expect(data.newRecovered).to.be(0);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v5AnalyticsTrendCountryGet', function() {
        it('should call v5AnalyticsTrendCountryGet successfully', function(done) {
          // TODO: uncomment, update parameter values for v5AnalyticsTrendCountryGet call and complete the assertions
          /*
          var startDate = "startDate_example";
          var endDate = "endDate_example";
          var opts = {};
          opts.countryCode = "countryCode_example";

          instance.v5AnalyticsTrendCountryGet(startDate, endDate, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(RmsCovidStatsCal.TrendCountry);
              expect(data.countryCode).to.be.a('string');
              expect(data.countryCode).to.be("");
              expect(data.country).to.be.a('string');
              expect(data.country).to.be("");
              expect(data.totalConfirmed).to.be.a('number');
              expect(data.totalConfirmed).to.be(0);
              expect(data.totalDeaths).to.be.a('number');
              expect(data.totalDeaths).to.be(0);
              expect(data.totalRecovered).to.be.a('number');
              expect(data.totalRecovered).to.be(0);
              expect(data.lastUpdated).to.be.a('string');
              expect(data.lastUpdated).to.be("");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
